apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge
type: Opaque
data:
  # Database Configuration (base64 encoded)
  DB_PG_HOST: cG9zdGdyZXMtc2VydmljZS50ZWNoLWNoYWxsZW5nZS5zdmMuY2x1c3Rlci5sb2NhbA==
  DB_PG_PORT: NTQzMg==
  DB_PG_USER: cG9zdGdyZXM=
  DB_PG_PASSWORD: cG9zdGdyZXM=
  DB_PG_NAME: cG9zdGdyZXM=
  DB_PG_LOGGING: dHJ1ZQ==
  
  # Application Configuration (base64 encoded)
  NODE_ENV: ZGV2
  API_KEY: eEZjdjhlZlh4dA==
  JWT_SECRET: a1lZM0s0UEgxVw==
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: M2Q=
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: N2Q=
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: tech-challenge
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: cG9zdGdyZXM=
