apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app-service
  namespace: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tech-challenge-app
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: tech-challenge
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: postgres
---
# NodePort service para acesso direto via IP do node
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app-nodeport
  namespace: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http
  selector:
    app: tech-challenge-app
---
# LoadBalancer service para expor a aplicação externamente
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-app-loadbalancer
  namespace: tech-challenge
  labels:
    app: tech-challenge-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tech-challenge-app
