name: microservice-customer

services:
  postgres:
    image: postgres:latest
    container_name: postgres-customer
    env_file:
      - .env
    ports:
      - '${DB_PG_PORT}:${DB_PG_PORT}'
    environment:
      - POSTGRES_USER=${DB_PG_USER}
      - POSTGRES_PASSWORD=${DB_PG_PASSWORD}
      - POSTGRES_DB=${DB_PG_NAME}
      - PGPORT=${DB_PG_PORT}
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${DB_PG_USER} -d ${DB_PG_NAME} -p ${DB_PG_PORT}',
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: app-customer
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1
      - NODE_ENV=development
      - DB_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
