version: '3.8'

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_PG_HOST: ${DB_PG_HOST}
      DB_PG_PORT: ${DB_PG_PORT}
      DB_PG_USER: ${DB_PG_USER}
      DB_PG_PASSWORD: ${DB_PG_PASSWORD}
      DB_PG_NAME: ${DB_PG_NAME}
      API_KEY: ${API_KEY}
      API_KEY_NAME_ORDER: ${API_KEY_NAME_ORDER}
      ORDER_SERVICE_BASE_URL_PARAM: ${ORDER_SERVICE_BASE_URL_PARAM}
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
      JWT_SECRET_NAME: ${JWT_SECRET_NAME}
      NODE_ENV: ${NODE_ENV}
      EXTERNAL_PAYMENT_CONSUMER_KEY: ${EXTERNAL_PAYMENT_CONSUMER_KEY}