name: ğŸš€ Deploy Infra & App

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'app/**'
      - 'infra/ecs/**'
      - 'terraform/**'
      - '.github/workflows/app.yml'

  push:
    branches:
      - develop
    paths:
      - 'app/**'
      - 'infra/ecs/**'
      - 'terraform/**'
      - '.github/workflows/app.yml'


jobs:

  build:
    name: ğŸ§ª Validate & Build
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.tags.outputs.version }}
      terraform_bucket: ${{ steps.bootstrap.outputs.bucket_name }}

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ” Terraform Format Check
        uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive

      - name: ğŸ” Terraform Validate
        working-directory: ./infra/ecs
        run: |
          terraform init -backend=false
          terraform validate

      - name: ğŸ›‘ Skip Build on PR
        if: github.event_name == 'pull_request'
        run: echo "Skipping deploy steps on PR..."

      - name: ğŸ”‘ Configure AWS Credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: ğŸª£ Bootstrap Terraform State Bucket
        if: github.event_name == 'push'
        id: bootstrap
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          BUCKET_NAME="terraform-state-${ACCOUNT_ID}"
          REGION="us-east-1"

          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT

      - name: ğŸ”“ Login to ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ğŸ·ï¸ Define Tags
        if: github.event_name == 'push'
        id: tags
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: ${{ secrets.REPOSITORY_ECR_NAME }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPO"
          TAGS="$IMAGE_URI:$COMMIT_HASH"

          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "version=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: ğŸ³ Build and Push
        if: github.event_name == 'push'
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: ${{ steps.tags.outputs.tags }}

  deploy:
    name: â˜ï¸ Deploy Terraform
    needs: build
    runs-on: ubuntu-latest

    if: github.event_name == 'push'  # ğŸ‘ˆ Aqui a chave do deploy

    defaults:
      run:
        working-directory: ./infra/ecs

    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@v4

      - name: ğŸ”‘ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: ğŸ› ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: ğŸ”„ Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ needs.build.outputs.terraform_bucket }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: ğŸš€ Terraform Apply
        env:
          TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
          TF_VAR_ecr_repository_name: ${{ secrets.REPOSITORY_ECR_NAME }}
          TF_VAR_image_tag: ${{ needs.build.outputs.image_tag }}
          TF_VAR_api_key: ${{ secrets.API_KEY }}
        run: |
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan
