name: üöÄ Deploy Infra & App

on:
  push:
    branches:
      - develop # alterar em prod para main
    paths:
      - 'app/**'
      - 'infra/ecs/**' 
      - 'terraform/**'
      - '.github/workflows/app.yml'
  pull_request:
    branches:
      - develop # alterar em prod para main
    paths:
      - 'app/**'
      - 'infra/ecs/**'
      - 'terraform/**'

jobs:
  build:
    name: üê≥ Build & Push Image
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tags.outputs.version }}
      terraform_bucket: ${{ steps.bootstrap.outputs.bucket_name }}
    
    steps:
      - name: üì• Checkout Code
        uses: actions/checkout@v4

      - name: üõ°Ô∏è Verify Build Secrets
        run: |
          if [[ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]]; then echo "‚ùå Erro: AWS_ACCESS_KEY_ID est√° vazio."; exit 1; fi
          if [[ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then echo "‚ùå Erro: AWS_SECRET_ACCESS_KEY est√° vazio."; exit 1; fi
          if [[ -z "${{ secrets.REPOSITORY_ECR_NAME }}" ]]; then echo "‚ùå Erro: REPOSITORY_ECR_NAME est√° vazio."; exit 1; fi
          echo "‚úÖ Todos os secrets de build est√£o presentes."

      - name: üîë Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} 
          aws-region: us-east-1

      - name: ü™£ Bootstrap Terraform State Bucket
        id: bootstrap
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          BUCKET_NAME="terraform-state-${ACCOUNT_ID}"
          REGION="us-east-1"
          
          if aws s3api head-bucket --bucket "$BUCKET_NAME" 2>/dev/null; then
            echo "Bucket exists."
          else
            echo "Creating bucket..."
            aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION"
          fi
          echo "bucket_name=$BUCKET_NAME" >> $GITHUB_OUTPUT

      - name: üìé Fetch DB Parameters (Build Args)
        id: ssm-params
        run: |
          PARAMS=$(aws ssm get-parameters --names "/db-customer-payment/main/rds_endpoint" "/db-customer-payment/main/db_username" "/db-customer-payment/main/db_password" --with-decryption --query "Parameters[].{Name:Name,Value:Value}" --output json)
          
          if [ "$PARAMS" == "[]" ]; then
            echo "‚ùå Erro: Par√¢metros n√£o encontrados no SSM"
            exit 1
          fi

          DB_HOST=$(echo $PARAMS | jq -r '.[] | select(.Name=="/db-customer-payment/main/rds_endpoint") | .Value')
          DB_USER=$(echo $PARAMS | jq -r '.[] | select(.Name=="/db-customer-payment/main/db_username") | .Value')
          DB_PASS=$(echo $PARAMS | jq -r '.[] | select(.Name=="/db-customer-payment/main/db_password") | .Value')

          # ‚úÖ ADICIONADO: Verifica√ß√£o se os par√¢metros do SSM vieram vazios
          if [[ -z "$DB_HOST" ]] || [[ -z "$DB_USER" ]] || [[ -z "$DB_PASS" ]]; then
             echo "‚ùå Erro: Um ou mais par√¢metros do SSM retornaram vazios."
             exit 1
          fi

          echo "DB_PG_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_PG_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_PG_PASSWORD=$DB_PASS" >> $GITHUB_ENV
          echo "::add-mask::$DB_PASS"

      - name: üîì Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: üè∑Ô∏è Define Tags
        id: tags
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPO: ${{ secrets.REPOSITORY_ECR_NAME }}
          COMMIT_HASH: ${{ github.sha }}
        run: |
          IMAGE_URI="$ECR_REGISTRY/$ECR_REPO"
          TAGS="$IMAGE_URI:$COMMIT_HASH"
          
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            TAGS="$TAGS,$IMAGE_URI:latest"
          fi
          
          echo "tags=$TAGS" >> $GITHUB_OUTPUT
          echo "version=$COMMIT_HASH" >> $GITHUB_OUTPUT

      - name: üèóÔ∏è Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üê≥ Build and Push
        id: docker-build
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tags.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            DB_PG_HOST=${{ env.DB_PG_HOST }}
            DB_PG_USER=${{ env.DB_PG_USER }}
            DB_PG_PASSWORD=${{ env.DB_PG_PASSWORD }}
            DB_PG_NAME=${{ secrets.DB_PG_NAME }}
            DB_PG_PORT=${{ secrets.DB_PG_PORT }}
            API_KEY=${{ secrets.API_KEY }}
            API_KEY_ORDER_SERVICE=${{ secrets.API_KEY_ORDER_SERVICE }}
            PARAM_URL_ORDER_SERVICE=${{ secrets.PARAM_URL_ORDER_SERVICE }}
            JWT_ACCESS_TOKEN_EXPIRATION_TIME=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }}
            JWT_SECRET_NAME=${{ secrets.JWT_SECRET_NAME }}
            NODE_ENV=production
            EXTERNAL_PAYMENT_CONSUMER_KEY=${{ secrets.EXTERNAL_PAYMENT_CONSUMER_KEY }}

  deploy:
    name: ‚òÅÔ∏è Deploy Terraform
    needs: build
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./infra/ecs
    
    steps:
      - name: üì• Checkout Code
        uses: actions/checkout@v4

      - name: üõ°Ô∏è Verify Deploy Variables
        env:
          VAR_PROJECT: ${{ secrets.PROJECT_NAME }}
          VAR_REPO: ${{ secrets.REPOSITORY_ECR_NAME }}
          VAR_API: ${{ secrets.API_KEY }}
          VAR_DB_NAME: ${{ secrets.DB_PG_NAME }}
        run: |
          if [[ -z "$VAR_PROJECT" ]]; then echo "‚ùå PROJECT_NAME vazio"; exit 1; fi
          if [[ -z "$VAR_REPO" ]]; then echo "‚ùå REPOSITORY_ECR_NAME vazio"; exit 1; fi
          if [[ -z "$VAR_API" ]]; then echo "‚ùå API_KEY vazia"; exit 1; fi
          if [[ -z "$VAR_DB_NAME" ]]; then echo "‚ùå DB_PG_NAME vazio"; exit 1; fi
          echo "‚úÖ Vari√°veis de ambiente verificadas."

      - name: üîë Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: üìé Fetch DB Parameters (Runtime)
        run: |
          PARAMS=$(aws ssm get-parameters --names "/db-customer-payment/main/rds_endpoint" "/db-customer-payment/main/db_username" "/db-customer-payment/main/db_password" --with-decryption --query "Parameters[].{Name:Name,Value:Value}" --output json)

          DB_HOST=$(echo $PARAMS | jq -r '.[] | select(.Name=="/db-customer-payment/main/rds_endpoint") | .Value')
          DB_USER=$(echo $PARAMS | jq -r '.[] | select(.Name=="/db-customer-payment/main/db_username") | .Value')
          DB_PASS=$(echo $PARAMS | jq -r '.[] | select(.Name=="/db-customer-payment/main/db_password") | .Value')

          if [[ -z "$DB_HOST" ]] || [[ -z "$DB_USER" ]]; then
             echo "‚ùå Erro Cr√≠tico: Falha ao recuperar par√¢metros do SSM para o Deploy."
             exit 1
          fi

          echo "DB_PG_HOST=$DB_HOST" >> $GITHUB_ENV
          echo "DB_PG_USER=$DB_USER" >> $GITHUB_ENV
          echo "DB_PG_PASSWORD=$DB_PASS" >> $GITHUB_ENV
          echo "::add-mask::$DB_PASS"

      - name: üõ†Ô∏è Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: üîÑ Terraform Init
        run: |
          terraform init \
            -backend-config="bucket=${{ needs.build.outputs.terraform_bucket }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=us-east-1"

      - name: üîé Terraform Validate & Plan
        env:
          TF_VAR_project_name: ${{ secrets.PROJECT_NAME }}
          TF_VAR_repository_ecr_name: ${{ secrets.REPOSITORY_ECR_NAME }}
          TF_VAR_api_key: ${{ secrets.API_KEY }}
          TF_VAR_db_pg_name: ${{ secrets.DB_PG_NAME }}
          TF_VAR_db_pg_port: ${{ secrets.DB_PG_PORT }}          
          TF_VAR_image_tag: ${{ needs.build.outputs.image_tag }}
          TF_VAR_db_pg_host: ${{ env.DB_PG_HOST }}
          TF_VAR_db_pg_username: ${{ env.DB_PG_USER }} 
          TF_VAR_db_pg_password: ${{ env.DB_PG_PASSWORD }}
          TF_VAR_api_key_order_service: ${{ secrets.API_KEY_ORDER_SERVICE }}
          TF_VAR_param_url_order_service: ${{ secrets.PARAM_URL_ORDER_SERVICE }}
          TF_VAR_jwt_access_token_expiration_time: ${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TIME }}
          TF_VAR_jwt_secret_name: ${{ secrets.JWT_SECRET_NAME }}
          TF_VAR_external_payment_consumer_key: ${{ secrets.EXTERNAL_PAYMENT_CONSUMER_KEY }}
        run: |
          echo "üîé Validando sintaxe..."
          terraform validate -no-color

          echo "üìã Gerando Plano (Speculative Plan)..."
          terraform plan -out=tfplan -no-color


      - name: üöÄ Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop' # alterar em prod para main
        run: |
          echo "üöÄ Aplicando Infraestrutura..."
          terraform apply -auto-approve -no-color tfplan